create table if not exists hh_oauth_sessions (
  state_hash text primary key,
  browser_hash text not null,
  verifier_box jsonb not null,
  issued_at timestamptz not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  check (expires_at <= issued_at + interval '10 minutes')
);
create index if not exists hh_oauth_sessions_expiry_idx on hh_oauth_sessions(expires_at);

create table if not exists hh_connections (
  id text primary key default 'hh-ru-employer',
  host text not null default 'hh.ru',
  application_id text not null,
  manager_id text,
  manager_name text,
  employer_id text,
  employer_name text,
  status text not null check (status in ('pending_review','active','disabled','recovery_required','conflict')),
  access_box jsonb,
  refresh_box jsonb,
  expires_at timestamptz,
  token_version bigint not null default 0,
  webhook_receiver_hash text,
  webhook_subscription_id text,
  last_sync_at timestamptz,
  last_error_code text,
  updated_at timestamptz not null default now(),
  check (host = 'hh.ru')
);

create table if not exists hh_vacancies (
  host text not null,
  employer_id text not null,
  vacancy_id text not null,
  name text,
  archived boolean,
  published_at timestamptz,
  snapshot_hash text not null,
  last_seen_at timestamptz not null default now(),
  primary key (host, employer_id, vacancy_id)
);

create table if not exists hh_negotiations (
  host text not null,
  employer_id text not null,
  negotiation_id text not null,
  vacancy_id text not null,
  resume_id text,
  applicant_state text,
  employer_state text,
  provider_created_at text,
  provider_updated_at text,
  detail_status text not null default 'not_read',
  metadata_hash text not null,
  person_id uuid,
  identity_status text not null default 'unlinked' check (identity_status in ('unlinked','manual_review','proved_link','conflict')),
  last_seen_at timestamptz not null default now(),
  primary key (host, employer_id, negotiation_id)
);
create index if not exists hh_negotiations_vacancy_idx on hh_negotiations(host, employer_id, vacancy_id);

create table if not exists hh_collection_memberships (
  host text not null,
  employer_id text not null,
  vacancy_id text not null,
  collection_id text not null,
  negotiation_id text not null,
  snapshot_hash text not null,
  last_seen_at timestamptz not null default now(),
  primary key (host, employer_id, vacancy_id, collection_id, negotiation_id)
);

create table if not exists hh_sync_checkpoints (
  host text not null,
  employer_id text not null,
  vacancy_id text not null,
  collection_id text not null,
  page integer not null check (page >= 0),
  collection_snapshot_hash text not null,
  page_hash text not null,
  found integer,
  pages integer,
  raw_rows integer not null,
  committed_at timestamptz not null default now(),
  primary key (host, employer_id, vacancy_id, collection_id, page, collection_snapshot_hash)
);

create table if not exists hh_webhook_events (
  host text not null,
  application_id text not null,
  subscription_id text not null,
  callback_id text not null,
  payload_hash text not null,
  event_type text not null,
  vacancy_id text,
  negotiation_id text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  primary key (host, application_id, subscription_id, callback_id)
);

create table if not exists hh_domain_events (
  id bigint generated by default as identity primary key,
  host text not null,
  employer_id text not null,
  vacancy_id text not null,
  negotiation_id text not null,
  event_kind text not null,
  idempotency_key text not null unique,
  occurred_at timestamptz not null default now()
);

create table if not exists hh_telegram_outbox (
  id bigint generated by default as identity primary key,
  event_id bigint not null references hh_domain_events(id),
  person_id uuid,
  journey_id uuid,
  event_kind text not null,
  template_ref text,
  correlation_id text not null,
  idempotency_key text not null unique,
  delivery_state text not null default 'awaiting_identity'
    check (delivery_state in ('awaiting_identity','queued','delivered','failed','cancelled')),
  attempt_count integer not null default 0,
  created_at timestamptz not null default now(),
  delivered_at timestamptz,
  check (delivery_state <> 'queued' or (person_id is not null and journey_id is not null and template_ref is not null))
);

create table if not exists hh_audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  status text not null,
  evidence_redacted jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

insert into schema_migrations(migration_id) values ('0011_hh_employer_inbound') on conflict do nothing;
